import type { Field, Plant, PlantType, Task, Note, ActivityLogEntry } from '../types';
import { addDays, subDays, format } from 'date-fns';

// Plant Types Catalog
export const defaultPlantTypes: PlantType[] = [
  {
    id: 'pt-1',
    name: 'Tomato',
    category: 'Vegetables',
    wateringFrequencyDays: 2,
    optimalTemperature: { min: 18, max: 29 },
    growthDuration: 80,
    commonPests: ['Aphids', 'Whiteflies', 'Hornworms'],
    commonDiseases: ['Blight', 'Fusarium wilt'],
    careInstructions: 'Water regularly, stake when tall, prune suckers',
  },
  {
    id: 'pt-2',
    name: 'Cucumber',
    category: 'Vegetables',
    wateringFrequencyDays: 1,
    optimalTemperature: { min: 20, max: 30 },
    growthDuration: 60,
    commonPests: ['Cucumber beetles', 'Spider mites'],
    commonDiseases: ['Powdery mildew', 'Downy mildew'],
    careInstructions: 'Keep soil consistently moist, provide trellis support',
  },
  {
    id: 'pt-3',
    name: 'Pepper',
    category: 'Vegetables',
    wateringFrequencyDays: 3,
    optimalTemperature: { min: 18, max: 32 },
    growthDuration: 90,
    commonPests: ['Aphids', 'Pepper weevils'],
    commonDiseases: ['Bacterial spot', 'Anthracnose'],
    careInstructions: 'Water deeply but less frequently, mulch to retain moisture',
  },
  {
    id: 'pt-4',
    name: 'Lettuce',
    category: 'Leafy Greens',
    wateringFrequencyDays: 1,
    optimalTemperature: { min: 10, max: 20 },
    growthDuration: 45,
    commonPests: ['Slugs', 'Aphids'],
    commonDiseases: ['Downy mildew', 'Bottom rot'],
    careInstructions: 'Keep cool, water frequently, harvest outer leaves',
  },
  {
    id: 'pt-5',
    name: 'Carrot',
    category: 'Root Vegetables',
    wateringFrequencyDays: 3,
    optimalTemperature: { min: 15, max: 24 },
    growthDuration: 75,
    commonPests: ['Carrot fly', 'Wireworms'],
    commonDiseases: ['Cavity spot', 'Root rot'],
    careInstructions: 'Keep soil loose and free of rocks, thin seedlings',
  },
  {
    id: 'pt-6',
    name: 'Strawberry',
    category: 'Fruits',
    wateringFrequencyDays: 2,
    optimalTemperature: { min: 15, max: 26 },
    growthDuration: 90,
    commonPests: ['Spider mites', 'Slugs'],
    commonDiseases: ['Gray mold', 'Powdery mildew'],
    careInstructions: 'Mulch around plants, remove runners for larger fruit',
  },
  {
    id: 'pt-7',
    name: 'Basil',
    category: 'Herbs',
    wateringFrequencyDays: 2,
    optimalTemperature: { min: 18, max: 30 },
    growthDuration: 60,
    commonPests: ['Aphids', 'Japanese beetles'],
    commonDiseases: ['Fusarium wilt', 'Downy mildew'],
    careInstructions: 'Pinch flowers to extend harvest, harvest leaves regularly',
  },
  {
    id: 'pt-8',
    name: 'Potato',
    category: 'Root Vegetables',
    wateringFrequencyDays: 4,
    optimalTemperature: { min: 15, max: 22 },
    growthDuration: 100,
    commonPests: ['Colorado potato beetle', 'Wireworms'],
    commonDiseases: ['Late blight', 'Scab'],
    careInstructions: 'Hill soil around plants as they grow, stop watering before harvest',
  },
];

const now = new Date();

// Sample Fields
export const sampleFields: Field[] = [
  {
    id: 'field-1',
    name: 'Main Vegetable Garden',
    area: 500,
    location: 'North section of farm',
    soilType: 'loam',
    zones: [
      {
        id: 'zone-1-1',
        fieldId: 'field-1',
        name: 'Zone A - Tomatoes',
        area: 150,
        soilType: 'loam',
        characteristics: 'Full sun, well-drained',
        createdAt: subDays(now, 60).toISOString(),
      },
      {
        id: 'zone-1-2',
        fieldId: 'field-1',
        name: 'Zone B - Peppers',
        area: 100,
        soilType: 'loam',
        characteristics: 'Partial shade, good drainage',
        createdAt: subDays(now, 60).toISOString(),
      },
      {
        id: 'zone-1-3',
        fieldId: 'field-1',
        name: 'Zone C - Leafy Greens',
        area: 250,
        soilType: 'loam',
        characteristics: 'Shaded area, moist soil',
        createdAt: subDays(now, 45).toISOString(),
      },
    ],
    notes: 'Primary growing area for vegetables. Irrigated with drip system.',
    status: 'healthy',
    createdAt: subDays(now, 90).toISOString(),
    updatedAt: subDays(now, 2).toISOString(),
  },
  {
    id: 'field-2',
    name: 'Herb Garden',
    area: 100,
    location: 'Near the main house',
    soilType: 'sandy',
    zones: [
      {
        id: 'zone-2-1',
        fieldId: 'field-2',
        name: 'Culinary Herbs',
        area: 60,
        soilType: 'sandy',
        characteristics: 'Full sun, fast drainage',
        createdAt: subDays(now, 30).toISOString(),
      },
      {
        id: 'zone-2-2',
        fieldId: 'field-2',
        name: 'Medicinal Herbs',
        area: 40,
        soilType: 'sandy',
        createdAt: subDays(now, 30).toISOString(),
      },
    ],
    notes: 'Small herb garden for kitchen use.',
    status: 'healthy',
    createdAt: subDays(now, 45).toISOString(),
    updatedAt: subDays(now, 5).toISOString(),
  },
  {
    id: 'field-3',
    name: 'Fruit Patch',
    area: 300,
    location: 'East side',
    soilType: 'loam',
    zones: [
      {
        id: 'zone-3-1',
        fieldId: 'field-3',
        name: 'Berry Section',
        area: 300,
        soilType: 'loam',
        characteristics: 'Slightly acidic soil',
        createdAt: subDays(now, 120).toISOString(),
      },
    ],
    notes: 'Strawberries and other berries.',
    status: 'attention',
    createdAt: subDays(now, 120).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
];

// Sample Plants
export const samplePlants: Plant[] = [
  {
    id: 'plant-1',
    name: 'Cherry Tomatoes',
    typeId: 'pt-1',
    type: defaultPlantTypes[0],
    fieldId: 'field-1',
    zoneId: 'zone-1-1',
    variety: 'Sweet 100',
    quantity: 24,
    plantedAt: subDays(now, 45).toISOString(),
    wateringFrequencyDays: 2,
    lastWateredAt: subDays(now, 1).toISOString(),
    nextWateringAt: addDays(now, 1).toISOString(),
    healthStatus: 'healthy',
    wateringStatus: 'watered',
    seedSource: 'Local nursery',
    notes: 'Growing well, starting to flower',
    photos: [],
    createdAt: subDays(now, 45).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'plant-2',
    name: 'Roma Tomatoes',
    typeId: 'pt-1',
    type: defaultPlantTypes[0],
    fieldId: 'field-1',
    zoneId: 'zone-1-1',
    variety: 'San Marzano',
    quantity: 18,
    plantedAt: subDays(now, 40).toISOString(),
    wateringFrequencyDays: 2,
    lastWateredAt: subDays(now, 3).toISOString(),
    nextWateringAt: subDays(now, 1).toISOString(),
    healthStatus: 'healthy',
    wateringStatus: 'overdue',
    seedSource: 'Saved seeds',
    notes: 'Need to stake soon',
    photos: [],
    createdAt: subDays(now, 40).toISOString(),
    updatedAt: subDays(now, 3).toISOString(),
  },
  {
    id: 'plant-3',
    name: 'Bell Peppers',
    typeId: 'pt-3',
    type: defaultPlantTypes[2],
    fieldId: 'field-1',
    zoneId: 'zone-1-2',
    variety: 'California Wonder',
    quantity: 12,
    plantedAt: subDays(now, 50).toISOString(),
    wateringFrequencyDays: 3,
    lastWateredAt: subDays(now, 2).toISOString(),
    nextWateringAt: addDays(now, 1).toISOString(),
    healthStatus: 'healthy',
    wateringStatus: 'watered',
    notes: 'Some peppers starting to form',
    photos: [],
    createdAt: subDays(now, 50).toISOString(),
    updatedAt: subDays(now, 2).toISOString(),
  },
  {
    id: 'plant-4',
    name: 'Romaine Lettuce',
    typeId: 'pt-4',
    type: defaultPlantTypes[3],
    fieldId: 'field-1',
    zoneId: 'zone-1-3',
    quantity: 30,
    plantedAt: subDays(now, 20).toISOString(),
    wateringFrequencyDays: 1,
    lastWateredAt: subDays(now, 2).toISOString(),
    nextWateringAt: subDays(now, 1).toISOString(),
    healthStatus: 'observation',
    wateringStatus: 'critical',
    notes: 'Showing signs of heat stress',
    photos: [],
    createdAt: subDays(now, 20).toISOString(),
    updatedAt: subDays(now, 2).toISOString(),
  },
  {
    id: 'plant-5',
    name: 'Sweet Basil',
    typeId: 'pt-7',
    type: defaultPlantTypes[6],
    fieldId: 'field-2',
    zoneId: 'zone-2-1',
    quantity: 8,
    plantedAt: subDays(now, 30).toISOString(),
    wateringFrequencyDays: 2,
    lastWateredAt: now.toISOString(),
    nextWateringAt: addDays(now, 2).toISOString(),
    healthStatus: 'healthy',
    wateringStatus: 'watered',
    notes: 'Harvest regularly to promote bushier growth',
    photos: [],
    createdAt: subDays(now, 30).toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'plant-6',
    name: 'Strawberries',
    typeId: 'pt-6',
    type: defaultPlantTypes[5],
    fieldId: 'field-3',
    zoneId: 'zone-3-1',
    variety: 'Seascape',
    quantity: 50,
    plantedAt: subDays(now, 90).toISOString(),
    wateringFrequencyDays: 2,
    lastWateredAt: subDays(now, 1).toISOString(),
    nextWateringAt: addDays(now, 1).toISOString(),
    healthStatus: 'sick',
    wateringStatus: 'due_soon',
    notes: 'Some plants showing signs of powdery mildew',
    photos: [],
    createdAt: subDays(now, 90).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'plant-7',
    name: 'Cucumbers',
    typeId: 'pt-2',
    type: defaultPlantTypes[1],
    fieldId: 'field-1',
    zoneId: 'zone-1-3',
    variety: 'Marketmore',
    quantity: 10,
    plantedAt: subDays(now, 35).toISOString(),
    wateringFrequencyDays: 1,
    lastWateredAt: now.toISOString(),
    nextWateringAt: addDays(now, 1).toISOString(),
    healthStatus: 'healthy',
    wateringStatus: 'watered',
    notes: 'Climbing well on trellis',
    photos: [],
    createdAt: subDays(now, 35).toISOString(),
    updatedAt: now.toISOString(),
  },
];

// Sample Tasks
export const sampleTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Water tomato plants',
    description: 'Check soil moisture and water if needed',
    dueDate: format(now, 'yyyy-MM-dd'),
    dueTime: '08:00',
    priority: 'high',
    status: 'pending',
    fieldId: 'field-1',
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Apply fertilizer to peppers',
    description: 'Use balanced NPK fertilizer',
    dueDate: format(addDays(now, 2), 'yyyy-MM-dd'),
    priority: 'medium',
    status: 'pending',
    fieldId: 'field-1',
    plantId: 'plant-3',
    createdAt: subDays(now, 3).toISOString(),
    updatedAt: subDays(now, 3).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Treat strawberry mildew',
    description: 'Apply organic fungicide to affected plants',
    dueDate: format(now, 'yyyy-MM-dd'),
    priority: 'high',
    status: 'pending',
    fieldId: 'field-3',
    plantId: 'plant-6',
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Harvest basil',
    description: 'Harvest leaves for kitchen use',
    dueDate: format(addDays(now, 1), 'yyyy-MM-dd'),
    priority: 'low',
    status: 'pending',
    fieldId: 'field-2',
    plantId: 'plant-5',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'task-5',
    title: 'Check lettuce health',
    description: 'Monitor for heat stress symptoms',
    dueDate: format(subDays(now, 1), 'yyyy-MM-dd'),
    priority: 'medium',
    status: 'pending',
    fieldId: 'field-1',
    plantId: 'plant-4',
    createdAt: subDays(now, 2).toISOString(),
    updatedAt: subDays(now, 2).toISOString(),
  },
];

// Sample Notes
export const sampleNotes: Note[] = [
  {
    id: 'note-1',
    type: 'observation',
    title: 'Tomato growth update',
    content: 'Cherry tomatoes showing excellent growth. First flowers appearing, expect fruit in 2-3 weeks.',
    fieldId: 'field-1',
    plantId: 'plant-1',
    photos: [],
    tags: ['tomato', 'growth', 'flowering'],
    isPrivate: false,
    createdAt: subDays(now, 3).toISOString(),
    updatedAt: subDays(now, 3).toISOString(),
  },
  {
    id: 'note-2',
    type: 'disease',
    title: 'Powdery mildew on strawberries',
    content: 'Noticed white powdery spots on several strawberry leaves. Need to treat with fungicide.',
    fieldId: 'field-3',
    plantId: 'plant-6',
    photos: [],
    tags: ['strawberry', 'disease', 'mildew'],
    isPrivate: false,
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 'note-3',
    type: 'watering',
    title: 'Adjusted watering schedule',
    content: 'Due to hot weather, increased watering frequency for lettuce from every other day to daily.',
    fieldId: 'field-1',
    plantId: 'plant-4',
    photos: [],
    tags: ['watering', 'lettuce', 'weather'],
    isPrivate: false,
    createdAt: subDays(now, 5).toISOString(),
    updatedAt: subDays(now, 5).toISOString(),
  },
];

// Sample Activity Log
export const sampleActivityLog: ActivityLogEntry[] = [
  {
    id: 'act-1',
    type: 'watering',
    action: 'complete',
    description: 'Watered Cherry Tomatoes',
    entityId: 'plant-1',
    entityType: 'plant',
    timestamp: subDays(now, 1).toISOString(),
  },
  {
    id: 'act-2',
    type: 'watering',
    action: 'complete',
    description: 'Watered Sweet Basil',
    entityId: 'plant-5',
    entityType: 'plant',
    timestamp: now.toISOString(),
  },
  {
    id: 'act-3',
    type: 'note',
    action: 'create',
    description: 'Added note about strawberry mildew',
    entityId: 'note-2',
    entityType: 'note',
    timestamp: subDays(now, 1).toISOString(),
  },
  {
    id: 'act-4',
    type: 'planting',
    action: 'create',
    description: 'Planted 10 Cucumber seedlings',
    entityId: 'plant-7',
    entityType: 'plant',
    timestamp: subDays(now, 35).toISOString(),
  },
  {
    id: 'act-5',
    type: 'problem',
    action: 'create',
    description: 'Detected disease on Strawberries',
    entityId: 'plant-6',
    entityType: 'plant',
    timestamp: subDays(now, 1).toISOString(),
  },
];

// Initialize stores with seed data
export function initializeSeedData(
  setFields: (fields: Field[]) => void,
  setPlants: (plants: Plant[]) => void,
  setPlantTypes: (types: PlantType[]) => void,
  addTask: (task: Task) => void,
  addNote: (note: Note) => void,
  _addActivity: (entry: Omit<ActivityLogEntry, 'id' | 'timestamp'>) => void
) {
  // Check if data already exists
  const existingFields = localStorage.getItem('farm-plus-fields');
  const existingPlants = localStorage.getItem('farm-plus-plants');

  if (!existingFields || JSON.parse(existingFields).state?.fields?.length === 0) {
    setFields(sampleFields);
  }

  if (!existingPlants || JSON.parse(existingPlants).state?.plants?.length === 0) {
    setPlantTypes(defaultPlantTypes);
    setPlants(samplePlants);
  }

  // Initialize tasks and notes if empty
  const existingUI = localStorage.getItem('farm-plus-ui');
  if (!existingUI || JSON.parse(existingUI).state?.tasks?.length === 0) {
    sampleTasks.forEach(addTask);
    sampleNotes.forEach(addNote);
  }
}
